version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Etc/Greenwich
  ignore:
  - dependency-name: grunt
    versions:
    - 1.3.0
